### PR TITLE
Feeder Page updated to use FirebaseAuth

### PR DESCRIPTION
**Pull request by JaydenBea**
Functionality added:

- Feeder Page now properly uses the information of the signed-in user
  - User can only edit entries that are their own. If user is an admin, they can edit any entry.
  - Selecting empty entries and confirming them assigns the user to those entries, not a hard-coded value.
- Methods/attributes in UserGoogle are now static
- Old methods/attributes in Snapshots and FirebaseHelper that used hard-coded "current user" values have been removed
- Long-deprecated files in Feeder Files have been removed

### CODE REVIEW

**Comment by nay-su** [comment]
👍

**Comment by JaydenBea** [comment]
12:30am, since 12am: Just added fix for automatic entry generation. It once again occurs as normal, this time accounting for station timespans.

**Comment by nay-su** [comment]
ok

**Comment by MMSU-1987** [comment]
cool

**Pull request closed without merging**
